#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  5 23:19:23 2023

@author: gonzalodes
"""

elementos_quimicos = ["hydrogen", "helium", "lithium", "beryllium", "boron", "carbon", "nitrogen", "oxygen",
 "fluorine", "neon", "sodium", "magnesium", "aluminum", "silicon", "phosphorus", "sulfur",
 "chlorine", "argon", "potassium", "calcium", "scandium", "titanium", "vanadium", "chromium",
 "manganese", "iron", "cobalt", "nickel", "copper", "zinc", "gallium", "germanium", "arsenic",
 "selenium", "bromine", "krypton", "rubidium", "strontium", "yttrium", "zirconium", "niobium",
 "molybdenum", "technetium", "ruthenium", "rhodium", "palladium", "silver", "cadmium", "indium",
 "tin", "antimony", "tellurium", "iodine", "xenon", "cesium", "barium", "lanthanum", "cerium",
 "praseodymium", "neodymium", "promethium", "samarium", "europium", "gadolinium", "terbium",
 "dysprosium", "holmium", "erbium", "thulium", "ytterbium", "lutetium", "hafnium", "tantalum",
 "tungsten", "rhenium", "osmium", "iridium", "platinum", "gold", "mercury", "thallium", "lead",
 "bismuth", "polonium", "astatine", "radon", "francium", "radium", "actinium", "thorium", "protactinium",
 "uranium", "neptunium", "plutonium", "americium", "curium", "berkelium", "californium", "einsteinium",
 "fermium", "mendelevium", "nobelium"]
y = []
def chemical_game(x):
    elementos_quimicos.remove(x)
    y.append(x)
    for i in elementos_quimicos:
        if x[-1]==i[0]:
            return chemical_game(i)
        else:
            print(i)
        


x = input("Enter a chemical element: ")

game = chemical_game(x)

print(f"The list goes as following:{y}")
