#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  5 15:05:45 2023

@author: gonzalodes
"""

def binary(x):
    if x<0:
        raise ValueError("Wrong input, must be positive")
    elif x>1:
        binary(x//2)
    print(x % 2, end="")    

x=int(input("Enter a non negative integer: "))

binary(x)
            
            
