#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 12 12:48:29 2023

@author: gonzalodes
"""

def Hanoi(n, i, j, k):
    if n==1:
        return print(f"\nDisk {n} was moved from rod {i} to rod {j}")
    else:
        Hanoi(n-1, i, k, j)
        print(f"\nDisk {n} was moved from rod {i} to rod {j}")
        Hanoi(n-1, k, j, i)
    
n = int(input("Number of disks: "))

Hanoi(n, "1", "3", "2")
